# MySQL. Versions 5.6.4 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  # QUAN TRỌNG: Dùng IP để tránh lỗi socket XAMPP trên Linux
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: kanji_together_db

test:
  <<: *default
  database: kanji_together_db_test

production:
  primary: &primary_production
    <<: *default
    database: kanji_together_db_production
    username: kanji_together_admin
    password: <%= ENV["KANJI_TOGETHER_ADMIN_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: kanji_together_admin_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: kanji_together_admin_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: kanji_together_admin_production_cable
    migrations_paths: db/cable_migrate